### ISSUE TITLE
Cannot convert pdf to html

### ISSUE THREAD

**Issue by thatgriffith** [shebinleo/pdf2html#6]
I've started up a nodejs project and installed `pdf2html?. However, whenever I try to run `pdf2html.html()` i get the following error message:

```
java -jar /Users/<path to project>/node_modules/pdf2html/vendor/tika-app-1.22.jar --html ./mock/example.pdf
Oct 08, 2020 10:27:51 AM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.

Oct 08, 2020 10:27:51 AM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: org.xerial's sqlite-jdbc is not loaded.
Please provide the jar on your classpath to parse sqlite files.
See tika-parsers/pom.xml for the correct version.
Exception in thread "main" java.net.MalformedURLException: no protocol: ./mock/example.pdf
        at java.base/java.net.URL.<init>(URL.java:668)
        at java.base/java.net.URL.<init>(URL.java:564)
        at java.base/java.net.URL.<init>(URL.java:511)
        at org.apache.tika.cli.TikaCLI.process(TikaCLI.java:488)
        at org.apache.tika.cli.TikaCLI.main(TikaCLI.java:149)
```

How do I solve this?

**Comment by heartworkscreative** [comment]
you need to replace tika-app-1.22.jar with the new one,  the path on npm modules, search folder pdf2html/vendor.
than on constant.js you should replace the VENDOR_TIKA_JAR with name of new jar.
